spring.application.name=banco_sociedad

# H2
spring.datasource.url=jdbc:h2:mem:bancodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# EJECUCIONES JOBS
spring.batch.job.name=dailyTransactionJob
#spring.batch.job.name=quarterlyInterestJob
#spring.batch.job.name=annualStatementJob

# Spring Batch
spring.batch.jdbc.initialize-schema=always
